version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:15.11.6-ce.0'
    hostname: 'localhost'
    ports:
      - '8000:80'
      - '2200:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '512m'
